# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=0.1.0
group=com.msbedwars

# Dependencies
fabric_api_version=0.155.3+26.1.2

# Scrapes hypixel.net player pages
jsoup_version=1.21.1

# Configure button in Mod Menu, optional at runtime
modmenu_version=18.0.0
